version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
 # Spring Boot Application Service
  spring-app:
    image: tahajerbi/devopsproject:BackImage
    container_name: SpringBack
    restart:  on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8082"
    depends_on:
      - mysql
volumes:
  db:
  

